### ISSUE TITLE
Error deploying using RancherUI

### ISSUE THREAD

**Issue by bkraegelin** [jhpyle/charts#5]
I try to deploy in my 3-Node Kubernetes Cluster using Rancher UI. (But this should not raise any problems.)
I changed tho following:

daHostname: docassemble.localnet
ingress-nginx.controller.service.type: NodePort
timeZone: Europe/Berlin
usingSslTermination: false

I get the following error message:
`Service does not have load balancer ingress IP address: default/docassemble-docassemble-service`

Any suggestions?

Thanks,
Birger

**Comment by bkraegelin** [comment]
Still no success.

I tried different deplyments with different values. My latest incarnation gets stuck on initializing backend
`wget: can't connect to remote host (10.43.212.239): Connection timed out`
`waiting for backend`

and initializing minio
`mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://mydocassemble-minio:9000/probe-bucket-sign-dsf3al0s5mfo/?location=": dial tcp 10.43.32.169:9000: i/o timeout.`

I run a brand new 7-node full-fledged HA Kubernetes cluster running K3S on top SUSE MicroOS with integrated traefik proxy.
I have no idea where to look for.

Thanks, Birger

**Comment by jhpyle** [comment]
I published a new version yesterday so you should try that if you aren't already trying it.

Regarding the first error you reported, I am not sure if you are listing a YAML file in your post. If it is a YAML file, it should be:

```
daHostname: docassemble.localnet
ingress-nginx:
  controller:
    service:
      type: NodePort
timeZone: Europe/Berlin
usingSslTermination: false
```

If you need to use `NodePort` you might also need the following:

```
ingress-nginx:
  controller:
    admissionWebhooks:
      patch:
        enabled: false
      enabled: false
    service:
      type: NodePort
```

I have tested the chart on Minikube and EKS. I have not tested on SUSE/MicroOS/traefik/Rancher.

On Minikube I need to set the `ingress-nginx` to the above. Even then I haven't been able to get `ingress-nginx` to connect to an IP on Minikube, so I do port-forward on the docassemble service, bypassing `ingress-nginx`. That is probably due to the limitations of Minikube.

On EKS the `ingress-nginx` default values work fine and I can set up external DNS by creating a CNAME pointing to the hostname reported by `kubectl get ingress`.

My experience with the MinIO subchart is that it tends to fail in inexplicable ways. It works consistently if 1) I use machines with at least 4GB of RAM; 2) the machines are freshly created; if I try to run MinIO after doing `helm delete` and `kubectl delete` then it often fails to start.

Every Kubernetes platform I have tried gives me new and different errors that are extremely difficult to debug. Typically the issues arise out of the subcharts and I have to change subchart configuration values through trial and error until something works.

Some tools I have found helpful for debugging are:

- Unpacking the subcharts in docassemble/charts and reviewing the `values.yaml` files for hints.
- Searching the web for documentation on the subcharts (which can be difficult to find) and reading it for hints.
- Using `helm template` to see what the computed configuration is.
- `kubectl describe` to see what is going on with a stalled resource.
- `kubectl logs` with the -c option for viewing the logs of init containers.
- `kubectl exec` with `/bin/bash` to go inside of a pod to see what is going on.

MinIO is especially troublesome. I once spent two weeks trying to get the official MinIO Helm chart to work, with no luck. Luckily the bitnami chart exists so I was able to use that instead.

`ingress-nginx` is also very confusing. The only reason I use it is to support sticky sessions when using websockets (the Live Help feature). I don't understand that chart and the documentation is very sparse. It seems to be better than `nginx-ingress`, though.

The only reason I use MinIO at all is because someone wanted docassemble to be deployable on-premises with no external dependencies. If I was hosting a Kubernetes implementation I would set `inClusterMinio: false` and use AWS S3.

Also, I have not gotten it to work on Kubernetes 1.24. I could get it to work on 1.23.8, though.

**Comment by bkraegelin** [comment]
Thanks for your kind help, I managed to get it running. I still have problems with RabbitMQ so I disabled the `inClusterRabbitMQ `service. I will give it another chance after verifying everything else.

My configuration is:
```
daHostname: docassemble.localnet
ingress-nginx:
  controller:
    service:
      type: NodePort
timeZone: Europe/Berlin
usingSslTermination: false
inClusterRabbitMQ: false
```
The ingress using nginx does not seem to work in my environment. I created a new one for traefik/https, now I'm able to connect to the start page.

I have Kubernetes K3S v1.24.3+k3s1, Rancher UI 2.6.6, openSUSE MicroOS. MicroOS upgrades are automatic, K3S upgrades are automatic using `system-upgrade-controller`.

My intention is to get everything running without modification so I will be able to install using Rancher UI directly from your chart repostitory. I just have to figure out the minimal set of configuration values for my environment.
